// ============================================================================
// MIGRATION NOTE — v3.0 Full Rebuild (2026-03-26)
// Old sheets: Hızlı Veri Girişi, Borç Takibi, Alacak Takibi, Nakit Akışı,
//             Dashboard, Aksiyon Merkezi, Ana Kontrol Paneli, Stok Yatırım Planı
// New sheets: Sabit Giderler, Stok Envanter, Stok Hareketleri, SKU Karlılık,
//             İthalat Planı, Talep ve Stok Baskısı, Risk Paneli
// Major upgrades:
//  - Full capital allocation & import timing decision engine
//  - Revenue capacity modeled as f(stock, turnover, stockout risk)
//  - Dynamic minimum cash reserve (not hardcoded)
//  - Multi-bucket 30/60/90 day cash projection
//  - SKU-level profitability, import scoring, stock intelligence
//  - Marketplace net payout modeling (commission, shipping, ads deductions)
//  - Fixed expense auto-generation into Borç Takibi
//  - Risk panel aggregating all business risks
//  - Actionable command-output Aksiyon Merkezi
// ============================================================================

// ─── 1. CONFIG ──────────────────────────────────────────────────────────────
var CONFIG = {
  // Sheet names
  sheets: {
    ana: "Ana Kontrol Paneli",
    giris: "Hızlı Veri Girişi",
    alacak: "Alacak Takibi",
    borc: "Borç Takibi",
    sabit: "Sabit Giderler",
    nakit: "Nakit Akışı",
    stok: "Stok Envanter",
    skuKar: "SKU Karlılık",
    ithalat: "İthalat Planı",
    talep: "Talep ve Stok Baskısı",
    risk: "Risk Paneli",
    dashboard: "Dashboard",
    aksiyon: "Aksiyon Merkezi",
    parametreler: "Parametreler",
    tahmin: "Tahmini Satışlar",
    krediKarti: "Kredi Kartları",
    acikHesap: "Açık Hesap Müşteriler",
    sistemLog: "Sistem Logları",
    cleanData: "CLEAN_DATA",
  },

  // Data layout
  headerRow: 1,
  dataStartRow: 2,
  lockTimeoutMs: 30000,
  timezone: "Europe/Istanbul",
  dateFormat: "dd.MM.yyyy",
  spreadsheetIds: {
    live: "1PeLF3CGuVZgHwrKiWhmr2Q9owMaElXtHVa5CTQzwUfc",
    test: "",
  },

  // Param cache (populated by loadParams_)
  params: {},

  // Key prefixes
  prefixes: {
    giris: "HVG",
    alacak: "ALC",
    borc: "BRC",
    sabit: "SBT",
    stok: "STK",
    hareket: "HRK",
    ithalat: "IMP",
    risk: "RSK",
    krediKarti: "KRT",
    acikHesap: "AHS",
  },

  // Cash projection
  projectionDays: 90,
  cashReserveMultiplier: 1.0, // months of fixed expenses
  debtReserveMultiplier: 1.0, // months of mandatory obligations
  delayBufferDays: 7, // extra days buffer

  // Stock intelligence
  defaultTurnoverCoeff: 0.25, // monthly revenue ≈ 25% of stock value
  safetyStockDays: 14,
  defaultLeadTimeDays: 30,

  // Import scoring weights (sum to ~1.0)
  importWeights: {
    roi: 0.2,
    salesVelocity: 0.2,
    stockoutUrgency: 0.25,
    demandConfidence: 0.1,
    cashPressure: -0.1,
    leadTimeRisk: -0.05,
    slowMoving: -0.1,
  },

  // Dropdown options
  options: {
    islemTipi: [
      "Tahsilat",
      "Ödeme",
      "İthalat Siparişi",
      "Stok Yatırımı",
      "Masraf",
      "Kart Harcaması",
      "Borç Ödemesi",
      "Sabit Gider",
      "Vergi",
      "Finansman",
      "Pazaryeri Kesintisi",
      "İade/Zarar",
      "Transfer",
    ],
    paraBirimi: ["TRY", "USD", "EUR", "RMB", "GBP"],
    durum: ["Planlandı", "Gerçekleşti", "Beklemede", "İptal"],
    oncelik: ["Düşük", "Orta", "Yüksek", "Kritik"],
    borcTuru: [
      "Maaş",
      "Kira",
      "Fatura",
      "Vergi",
      "Kredi Kartı",
      "Kredi Taksidi",
      "Banka Kredisi",
      "Ticari Borç",
      "Tedarikçi",
      "İthalat Ödemesi",
      "Gümrük",
      "Kargo",
      "Diğer",
    ],
    borcDurum: ["Planlandı", "Ödendi", "Gecikmiş", "Ertelendi", "İptal"],
    alacakDurum: ["Bekleniyor", "Tahsil Edildi", "Gecikmeli", "İptal"],
    stokDurum: ["Kritik", "Düşük", "Normal", "Fazla", "Ölü Stok"],
    hareketTuru: [
      "İthalat Girişi",
      "Satış Çıkışı",
      "İade Girişi",
      "Hasar/Zayi",
      "Sayım Farkı",
      "Transfer",
    ],
    siparisKarari: [
      "Şimdi Sipariş Ver",
      "Yakında Sipariş Ver",
      "Bekle",
      "Alma",
    ],
    ithalatDurum: [
      "Planlandı",
      "Sipariş Verildi",
      "Ödeme Kısmen Yapıldı",
      "Yolda",
      "Gümrükte",
      "Teslim Alındı",
      "İptal",
    ],
    tasimaType: ["Hava Kargo", "Deniz Yükü"],
    riskTipi: [
      "Nakit Sıkışıklığı",
      "Stok Tükenmesi",
      "Gecikmiş Alacak",
      "Gecikmiş Borç",
      "Kur Riski",
      "Tedarik Riski",
      "Talep Düşüşü",
      "Ölü Stok",
      "Yüksek Borç Servis Baskısı",
      "Kredi Kartı Limit Baskısı",
      "Açık Hesap Yoğunlaşması",
      "Diğer",
    ],
    giderKategori: [
      "Maaş",
      "Kira",
      "Fatura",
      "Vergi",
      "Kredi Kartı",
      "Kredi Taksidi",
      "Sigorta",
      "Abonelik",
      "Diğer",
    ],
    kanal: [
      "Amazon",
      "Trendyol",
      "Hepsiburada",
      "N11",
      "Kendi Sitesi",
      "Toptan",
      "Diğer",
    ],
    evetHayir: ["Evet", "Hayır"],
    tekrarlamaTipi: ["Aylık", "İki Aylık", "Üç Aylık", "Yıllık"],
    sabitDurum: ["Aktif", "Donduruldu", "İptal"],
    kartDurum: ["Aktif", "Donduruldu", "İptal"],
    odemeTercihi: ["Tam Ödeme", "Asgari Ödeme"],
    tahsilDurum: [
      "Vadesi Gelmedi",
      "Bugün Tahsil Edilmeli",
      "Geciken",
      "Kısmi Tahsil Edildi",
      "Tahsil Edildi",
      "Riskli / İhtilaflı",
    ],
  },
};

// ─── 2. SCHEMA DEFINITIONS ─────────────────────────────────────────────────
var SCHEMAS = {};

SCHEMAS[CONFIG.sheets.giris] = [
  "Kayıt ID",
  "İşlem Tarihi",
  "Nakit Etki Tarihi",
  "İşlem Tipi",
  "Alt Kategori",
  "Kanal / Karşı Taraf",
  "Ürün Grubu",
  "SKU",
  "Tutar",
  "Para Birimi",
  "Kur",
  "Tutar TL",
  "Vade Tarihi",
  "Durum",
  "Öncelik",
  "Kur",
  "Tutar TL",
  "Ayın Günü",
  "Tekrarlama Tipi",
  "Başlangıç Tarihi",
  "Bitiş Tarihi",
  "Artış Tarihi",
  "Revize Tutar",
  "Zorunlu mu",
  "Kesilebilir mi",
  "Departman",
  "Sonraki Oluşturma Tarihi",
  "Durum",
];

SCHEMAS[CONFIG.sheets.nakit] = [
  "Tarih",
  "Açılış Bakiye",
  "Kesin Giriş",
  "Olası Giriş",
  "Kesin Çıkış",
  "Olası Çıkış",
  "Operasyonel Çıkış",
  "İthalat Çıkışı",
  "Finansman Girişi",
  "Tahmini Kapanış Bakiye",
  "Min Güvenli Nakit",
  "Kullanılabilir Alım Kapasitesi",
  "Alarm",
  "Not",
];

SCHEMAS[CONFIG.sheets.stok] = [
  "SKU",
  "Ürün Adı",
  "Kategori",
  "Tedarikçi",
  "Mevcut Adet",
  "Aylık Satış Potansiyeli",
  "İthalat Maliyeti (USD)",
  "Ortalama Net Kar Marjı (%)",
  "Birim Maliyet USD",
  "Birim Satış Fiyatı USD",
  "Mevcut Stok Değeri USD",
  "Son 30 Gün Satış Adedi",
  "Son 90 Gün Satış Adedi",
  "Günlük Ortalama Satış",
  "Günlük Ortalama Net Ciro USD",
  "Aylık Dönüş Katsayısı",
  "Stok Gün Sayısı",
  "Güvenlik Stoğu Gün",
  "İthalat Lead Time Gün",
  "Yeniden Sipariş Noktası",
  "Tahmini Stok Bitiş Tarihi",
  "Stok Durumu",
  "Stok Yaşlanma Puanı",
  "Sermaye Verim Puanı",
  "Olası 30 Gün Ciro Kaybı",
  "Olası 30 Gün Kar Kaybı",
  "Öncelik Skoru",
];

SCHEMAS[CONFIG.sheets.skuKar] = [
  "SKU",
  "Ürün Adı",
  "Kategori",
  "Son 30 Gün Satış",
  "Son 90 Gün Satış",
  "Ortalama Satış Fiyatı",
  "Ortalama Net Satış",
  "Birim Tam Maliyet",
  "Brüt Marj %",
  "Net Kar",
  "Net Kar Marjı %",
  "ROI",
  "Günlük Satış Hızı",
  "Stok Gün Sayısı",
  "Transit Gün",
  "Tahsilat Gün",
  "Toplam Çevrim Süresi",
  "Finansman Maliyeti %",
  "Finansman Sonrası Net Getiri",
  "Yıllıklandırılmış Sermaye Verimi %",
  "Sermaye Verim Puanı",
  "Ürün Sınıfı",
  "Ölü Stok Riski",
  "Yeniden Sipariş Önceliği",
  "Stok Politika Kararı",
];

SCHEMAS[CONFIG.sheets.ithalat] = [
  "Plan Kodu",
  "SKU",
  "Ürün",
  "Tedarikçi",
  "Taşıma Tipi",
  "Sipariş Tarihi",
  "RMB Alış Fiyatı",
  "USD Alış Fiyatı",
  "Sipariş Kuru",
  "Ağırlık KG",
  "Kargo USD/KG",
  "Gümrük Oranı",
  "Toplam Birim Maliyet TL",
  "MOQ",
  "Sipariş Adedi",
  "Toplam Yatırım Tutarı TL",
  // Çok aşamalı ödeme
  "Mal Bedeli Ödeme Tarihi",
  "Mal Bedeli Tutarı",
  "Navlun Ödeme Tarihi",
  "Navlun Tutarı",
  "Gümrük Ödeme Tarihi",
  "Gümrük Tutarı",
  // Zaman modeli
  "Tahmini Varış Tarihi",
  "Tahmini Satış Başlangıcı",
  "Lead Time Gün",
  // Karlılık
  "Beklenen Satış Fiyatı",
  "Pazaryeri Net Satışı",
  "Birim Net Kar",
  "Toplam Net Kar",
  "ROI",
  "Tahmini Satış Süresi Gün",
  "Tahmini Nakit Dönüş Günü",
  // Karar
  "Risk Seviyesi",
  "Sipariş Kararı",
  "Gerekçe",
  "Durum",
];

SCHEMAS[CONFIG.sheets.talep] = [
  "SKU",
  "Mevcut Stok Değeri",
  "Son 30 Gün Net Satış",
  "Son 90 Gün Net Satış",
  "Satış Trend Katsayısı",
  "Stok Gün Sayısı",
  "Lead Time",
  "Güvenlik Stoğu",
  "Stok Açık Riski",
  "30 Günlük Tahmini Ciro",
  "60 Günlük Tahmini Ciro",
  "Stok Yetmezse Kaybedilecek Ciro",
  "Stok Yetmezse Kaybedilecek Kar",
  "İthalat Öncelik Skoru",
  "Karar",
];

SCHEMAS[CONFIG.sheets.risk] = [
  "Risk Kodu",
  "Risk Tipi",
  "İlgili SKU / İşlem",
  "Tutar Etkisi",
  "Etki Tarihi",
  "Olasılık",
  "Beklenen Zarar",
  "Aksiyon",
  "Sorumlu",
  "Durum",
];

SCHEMAS[CONFIG.sheets.parametreler] = [
  "Parametre Anahtarı",
  "Grup",
  "Etiket",
  "Değer",
  "Değer Tipi",
  "Birim",
  "Açıklama",
  "Kullanan Modüller",
  "Güncellenme Tarihi",
  "Güncelleyen",
];

SCHEMAS[CONFIG.sheets.tahmin] = [
  "Tahmin Kodu",
  "Tahmin Tarihi",
  "Ürün Grubu",
  "Senaryo",
  "Tahmini Satış Tutarı",
  "Tahmini Tahsilat Tarihi",
  "Güven Skoru",
  "Durum",
];

SCHEMAS[CONFIG.sheets.krediKarti] = [
  "Kart ID",
  "Kart Adı",
  "Banka",
  "Kredi Limiti",
  "Ekstre Kesim Günü",
  "Son Ödeme Günü",
  "Güncel Bakiye",
  "Asgari Ödeme Tutarı",
  "Para Birimi",
  "Ödeme Tercihi",
  "Durum",
  "Son Ekstre Tutarı",
  "Son Ödeme Tarihi",
  "Son Ödeme Tutarı",
  "Limit Kullanım %",
  "Sonraki Son Ödeme Tarihi",
  "Beklenen Ödeme Tutarı",
  "Risk Seviyesi",
  "Notlar",
];

SCHEMAS[CONFIG.sheets.acikHesap] = [
  "Alacak ID",
  "Müşteri Adı",
  "Belge / Sipariş No",
  "Kesim Tarihi",
  "Vade Tarihi",
  "Tutar",
  "Para Birimi",
  "Tahsil Durumu",
  "Tahsil Edilen Tutar",
  "Kalan Bakiye",
  "Gecikme Günü",
  "Risk Skoru",
  "Risk Seviyesi",
  "Öncelik",
  "Sonraki Aksiyon",
  "Son Tahsilat Notu",
];

SCHEMAS[CONFIG.sheets.rawSales] = [
  "Kayıt ID",
  "SKU",
  "Ürün Adı",
  "Kategori",
  "Satış Adedi",
  "Birim Fiyat",
  "Toplam Ciro",
  "Para Birimi",
  "Kur",
  "Ciro TL",
  "Satış Tarihi",
  "Kanal",
  "Komisyon Oranı",
  "Net Ciro TL",
  "Import Tarihi",
  "Kaynak Dosya",
];

SCHEMAS[CONFIG.sheets.rawStock] = [
  "SKU",
  "Ürün Adı",
  "Kategori",
  "Tedarikçi",
  "Mevcut Adet",
  "Birim Maliyet",
  "Toplam Stok Değeri",
  "Birim Satış Fiyatı",
  "Son 30 Gün Satış",
  "Son 90 Gün Satış",
  "Günlük Ortalama Satış",
  "Günlük Ortalama Ciro",
  "Import Tarihi",
  "Kaynak Dosya",
];

SCHEMAS[CONFIG.sheets.cleanData] = [
  "SKU",
  "Ürün Adı",
  "Kategori",
  "Tedarikçi",
  "Mevcut Adet",
  "Birim Maliyet TL",
  "Toplam Stok Değeri TL",
  "Birim Satış Fiyatı TL",
  "Son 30 Gün Satış Adedi",
  "Son 90 Gün Satış Adedi",
  "Toplam Satış Adedi",
  "Toplam Ciro TL",
  "Günlük Ortalama Satış",
  "Günlük Ortalama Ciro TL",
  "Komisyon Oranı",
  "Net Günlük Ciro TL",
  "Veri Kalite Notu",
  "Son Güncelleme",
];

SCHEMAS[CONFIG.sheets.dashboard] = []; // rendered by script
SCHEMAS[CONFIG.sheets.aksiyon] = []; // rendered by script
SCHEMAS[CONFIG.sheets.ana] = []; // rendered by script
SCHEMAS[CONFIG.sheets.sistemLog] = ["Tarih", "Kullanıcı", "Aksiyon", "Detay"];

// ─── 2b. PARAMETER ENGINE ───────────────────────────────────────────────────

var DEFAULT_PARAMS = [
  // Kur ve para birimi
  [
    "usd_try",
    "Kur",
    "USD/TRY",
    "34.50",
    "number",
    "TRY",
    "Güncel dolar kuru",
    "İthalat, Nakit Akışı",
  ],
  [
    "eur_try",
    "Kur",
    "EUR/TRY",
    "37.00",
    "number",
    "TRY",
    "Güncel euro kuru",
    "İthalat",
  ],
  // Nakit güvenliği
  [
    "safe_cash_floor",
    "Nakit",
    "Güvenli Nakit Alt Limiti",
    "200000",
    "number",
    "TRY",
    "Bakiyenin altına düşmemesi gereken minimum tutar",
    "Nakit Akışı, Karar Motoru, Dashboard",
  ],
  [
    "critical_cash_floor",
    "Nakit",
    "Kritik Nakit Alt Limiti",
    "50000",
    "number",
    "TRY",
    "Bakiye bu seviyenin altındaysa acil müdahale",
    "Karar Motoru",
  ],
  [
    "cash_warning_days",
    "Nakit",
    "Nakit Uyarı Gün Sayısı",
    "7",
    "number",
    "gün",
    "Bu gün ufkunda tampon kırılıyorsa uyarı",
    "Dashboard",
  ],
  // Projeksiyon
  [
    "projection_days",
    "Nakit",
    "Projeksiyon Gün Sayısı",
    "90",
    "number",
    "gün",
    "Nakit projeksiyonu kaç gün ileri bakacak",
    "Nakit Akışı",
  ],
  [
    "cash_reserve_multiplier",
    "Nakit",
    "Sabit Gider Rezerv Çarpanı",
    "1.0",
    "number",
    "ay",
    "Min güvenli nakit = sabit gider × bu çarpan",
    "Nakit Akışı",
  ],
  [
    "debt_reserve_multiplier",
    "Nakit",
    "Borç Rezerv Çarpanı",
    "1.0",
    "number",
    "ay",
    "Min güvenli nakit borç payı çarpanı",
    "Nakit Akışı",
  ],
  [
    "delay_buffer_days",
    "Nakit",
    "Gecikme Tampon Günü",
    "7",
    "number",
    "gün",
    "Nakit tampon hesabına eklenen ek güvenlik günü",
    "Nakit Akışı",
  ],
  // Transit ve lojistik
  [
    "sea_transit_days_default",
    "Lojistik",
    "Deniz Transit Süresi",
    "50",
    "number",
    "gün",
    "Varsayılan deniz kargo transit süresi",
    "İthalat Planı",
  ],
  [
    "air_transit_days_default",
    "Lojistik",
    "Hava Transit Süresi",
    "10",
    "number",
    "gün",
    "Varsayılan hava kargo transit süresi",
    "İthalat Planı",
  ],
  [
    "customs_clearance_days_default",
    "Lojistik",
    "Gümrük Süresi",
    "5",
    "number",
    "gün",
    "Varsayılan gümrük işlem süresi",
    "İthalat Planı",
  ],
  // Stok ve karlılık
  [
    "default_turnover_coeff",
    "Stok",
    "Varsayılan Devir Katsayısı",
    "0.25",
    "number",
    "",
    "Aylık ciro / stok değeri oranı varsayımı",
    "Stok Envanter, SKU Karlılık",
  ],
  [
    "safety_stock_days",
    "Stok",
    "Güvenlik Stok Günü",
    "14",
    "number",
    "gün",
    "Stok tükenmesine karşı güvenlik tamponu",
    "Stok Envanter, Talep Baskısı",
  ],
  [
    "default_lead_time_days",
    "Stok",
    "Varsayılan Tedarik Süresi",
    "30",
    "number",
    "gün",
    "Varsayılan ithalat lead time",
    "Stok Envanter, Talep Baskısı, İthalat",
  ],
  [
    "max_acceptable_inventory_turn_days",
    "Stok",
    "Maks Kabul Edilebilir Devir Süresi",
    "90",
    "number",
    "gün",
    "Bu sürenin üstünde stok yaşlanıyor",
    "Stok Envanter",
  ],
  [
    "stock_aging_warning_days",
    "Stok",
    "Stok Yaşlanma Uyarı Günü",
    "60",
    "number",
    "gün",
    "Bu günden sonra uyarı üretilir",
    "Dashboard",
  ],
  [
    "minimum_net_margin_threshold",
    "Stok",
    "Minimum Net Marj Eşiği",
    "0.10",
    "number",
    "%",
    "Bu marjın altındaki ürünler zayıf",
    "SKU Karlılık, Karar Motoru",
  ],
  [
    "discount_clearance_factor",
    "Stok",
    "Stok Eritme İndirim Katsayısı",
    "0.20",
    "number",
    "%",
    "Fiyat kırma kararında kullanılan indirim oranı",
    "Karar Motoru",
  ],
  [
    "default_collection_days",
    "Stok",
    "Varsayılan Tahsilat Süresi",
    "21",
    "number",
    "gün",
    "Pazaryeri tahsilat süresi varsayımı",
    "SKU Karlılık",
  ],
  [
    "annual_financing_rate",
    "Finansman",
    "Yıllık Finansman Maliyet Oranı",
    "0.50",
    "number",
    "%",
    "Sermaye maliyeti / yıllık finansman faiz oranı",
    "SKU Karlılık, Karar Motoru",
  ],
  [
    "marketplace_commission_rate",
    "Stok",
    "Pazaryeri Komisyon Oranı",
    "0.15",
    "number",
    "%",
    "Ortalama pazaryeri kesinti oranı",
    "SKU Karlılık, İthalat Planı",
  ],
  // İthalat ağırlıkları
  [
    "import_w_roi",
    "İthalat",
    "Ağırlık: ROI",
    "0.20",
    "number",
    "",
    "İthalat karar skoru ROI ağırlığı",
    "İthalat Planı",
  ],
  [
    "import_w_sales_velocity",
    "İthalat",
    "Ağırlık: Satış Hızı",
    "0.20",
    "number",
    "",
    "İthalat karar skoru satış hızı ağırlığı",
    "İthalat Planı",
  ],
  [
    "import_w_stockout_urgency",
    "İthalat",
    "Ağırlık: Stok Tükenme Aciliyeti",
    "0.25",
    "number",
    "",
    "İthalat karar skoru stok tükenme ağırlığı",
    "İthalat Planı",
  ],
  [
    "import_w_demand_confidence",
    "İthalat",
    "Ağırlık: Talep Güveni",
    "0.10",
    "number",
    "",
    "İthalat karar skoru talep güveni ağırlığı",
    "İthalat Planı",
  ],
  [
    "import_w_cash_pressure",
    "İthalat",
    "Ağırlık: Nakit Baskısı",
    "-0.10",
    "number",
    "",
    "İthalat karar skoru nakit baskısı ağırlığı (negatif)",
    "İthalat Planı",
  ],
  [
    "import_w_lead_time_risk",
    "İthalat",
    "Ağırlık: Lead Time Riski",
    "-0.05",
    "number",
    "",
    "İthalat karar skoru lead time risk ağırlığı (negatif)",
    "İthalat Planı",
  ],
  [
    "import_w_slow_moving",
    "İthalat",
    "Ağırlık: Yavaş Hareket",
    "-0.10",
    "number",
    "",
    "İthalat karar skoru yavaş stok ağırlığı (negatif)",
    "İthalat Planı",
  ],
  // Tahsilat
  [
    "collection_delay_factor",
    "Tahsilat",
    "Tahsilat Gecikme Katsayısı",
    "1.2",
    "number",
    "",
    "Beklenen tahsilat süresine uygulanan gecikme çarpanı",
    "Nakit Akışı, Karar Motoru",
  ],
  [
    "forecast_confidence_threshold",
    "Tahsilat",
    "Tahmin Güven Eşiği",
    "0.7",
    "number",
    "",
    "Bu güven skorunun altındaki tahminler karara girmez",
    "Karar Motoru",
  ],
  // Finansman
  [
    "max_acceptable_monthly_interest",
    "Finansman",
    "Maks Kabul Edilebilir Aylık Faiz",
    "0.035",
    "number",
    "%",
    "Bu faiz oranının üstünde kredi mantıksız",
    "Karar Motoru",
  ],
  [
    "minimum_dscr_threshold",
    "Finansman",
    "Minimum DSCR Eşiği",
    "1.2",
    "number",
    "",
    "Borç servis karşılama oranı alt limiti",
    "Karar Motoru",
  ],
  // Senaryo katsayıları
  [
    "conservative_sales_factor",
    "Senaryo",
    "Muhafazakâr Satış Katsayısı",
    "0.7",
    "number",
    "",
    "Muhafazakâr senaryoda satış çarpanı",
    "Tahmini Satışlar",
  ],
  [
    "normal_sales_factor",
    "Senaryo",
    "Normal Satış Katsayısı",
    "1.0",
    "number",
    "",
    "Normal senaryoda satış çarpanı",
    "Tahmini Satışlar",
  ],
  [
    "aggressive_sales_factor",
    "Senaryo",
    "Agresif Satış Katsayısı",
    "1.3",
    "number",
    "",
    "Agresif senaryoda satış çarpanı",
    "Tahmini Satışlar",
  ],
  // Başlangıç bakiyesi
  [
    "opening_cash_balance",
    "Nakit",
    "Başlangıç Nakit Bakiyesi",
    "0",
    "number",
    "TRY",
    "Nakit projeksiyonu başlangıç bakiyesi (ilk kurulum için)",
    "Nakit Akışı",
  ],
];

// ─── 3. SHEET UX METADATA ──────────────────────────────────────────────────
// Classification: INPUT, HYBRID, SYSTEM, PANEL, CONFIG, LOG

var SHEET_UX = {
  classifications: {
    ana: "PANEL",
    dashboard: "PANEL",
    aksiyon: "PANEL",
    giris: "INPUT",
    borc: "HYBRID",
    alacak: "HYBRID",
    sabit: "HYBRID",
    stok: "HYBRID",
    stokHareket: "HYBRID",
    ithalat: "HYBRID",
    krediKarti: "HYBRID",
    acikHesap: "HYBRID",
    nakit: "SYSTEM",
    skuKar: "SYSTEM",
    talep: "SYSTEM",
    tahmin: "SYSTEM",
    risk: "SYSTEM",
    parametreler: "CONFIG",
    sistemLog: "LOG",
    rawSales: "SYSTEM",
    rawStock: "SYSTEM",
    cleanData: "SYSTEM",
  },
  tabColors: {
    INPUT: "#34a853",
    HYBRID: "#4285f4",
    SYSTEM: "#ff8f00",
    PANEL: "#9334e6",
    CONFIG: "#5f6368",
    LOG: "#80868b",
    START: "#ea4335",
  },
  sheetOrder: [
    "START_HERE",
    "ana",
    "dashboard",
    "giris",
    "borc",
    "alacak",
    "sabit",
    "stok",
    "stokHareket",
    "ithalat",
    "krediKarti",
    "acikHesap",
    "nakit",
    "skuKar",
    "talep",
    "tahmin",
    "risk",
    "aksiyon",
    "parametreler",
    "rawSales",
    "rawStock",
    "cleanData",
    "sistemLog",
  ],
  systemColumns: {
    giris: ["Kayıt ID", "Tutar TL", "Oluşturulma", "Güncellenme"],
    borc: [
      "Borç Kodu",
      "Kalan Anapara",
      "Toplam Finansman Maliyeti",
      "Nakit Etki",
      "Gecikme Gün",
      "Risk",
      "Öncelik",
      "Sonraki Aksiyon",
    ],
    alacak: [
      "Alacak Kodu",
      "Beklenen Net Tahsilat",
      "Gün Kaldı",
      "Gecikme Gün",
      "Risk Puanı",
      "Öncelik",
      "Sonraki Aksiyon",
    ],
    sabit: ["Gider Kodu", "Tutar TL", "Sonraki Oluşturma Tarihi"],
    stok: [
      "Mevcut Stok Değeri TL",
      "Günlük Ortalama Satış",
      "Günlük Ortalama Net Ciro",
      "Aylık Dönüş Katsayısı",
      "Stok Gün Sayısı",
      "Güvenlik Stoğu Gün",
      "İthalat Lead Time Gün",
      "Yeniden Sipariş Noktası",
      "Tahmini Stok Bitiş Tarihi",
      "Stok Durumu",
      "Stok Yaşlanma Puanı",
      "Sermaye Verim Puanı",
      "Olası 30 Gün Ciro Kaybı",
      "Olası 30 Gün Kar Kaybı",
      "Öncelik Skoru",
    ],
    stokHareket: ["Hareket ID", "Toplam Maliyet TL"],
    ithalat: [
      "Plan Kodu",
      "Toplam Birim Maliyet TL",
      "Toplam Yatırım Tutarı TL",
      "Pazaryeri Net Satışı",
      "Birim Net Kar",
      "Toplam Net Kar",
      "ROI",
      "Tahmini Satış Süresi Gün",
      "Tahmini Nakit Dönüş Günü",
      "Risk Seviyesi",
      "Sipariş Kararı",
      "Gerekçe",
    ],
    krediKarti: [
      "Kart ID",
      "Limit Kullanım %",
      "Sonraki Son Ödeme Tarihi",
      "Beklenen Ödeme Tutarı",
      "Risk Seviyesi",
    ],
    acikHesap: [
      "Alacak ID",
      "Tahsil Durumu",
      "Kalan Bakiye",
      "Gecikme Günü",
      "Risk Skoru",
      "Risk Seviyesi",
      "Öncelik",
      "Sonraki Aksiyon",
    ],
  },
};
